spring:
    application:
        name: demo
    datasource:
        url: jdbc:mysql://localhost:3306/hospital
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver